<a href="https://colab.research.google.com/github/amartin6251/2023_Work/blob/main/TensorFlow2Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#TensorFlow 2 practice
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.9.2


In [9]:
#Download and split MNIST training data
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [10]:
#TF Sequential model creation

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [11]:
#Create and run a predictions variable
#Output is a set of logits (non-normalized vectors)
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.5657599 ,  0.4972469 ,  0.27225724, -1.0136293 , -0.00890909,
         0.13808653,  0.6293537 , -0.6217305 ,  0.26914382,  0.21192831]],
      dtype=float32)

In [12]:
#Softmax to convert logits to probabilities (normalized) for multiclass classification
tf.nn.softmax(predictions).numpy()

array([[0.14458361, 0.13500947, 0.10780837, 0.02979882, 0.08138483,
        0.09427203, 0.15407689, 0.04409593, 0.10747324, 0.10149671]],
      dtype=float32)

In [14]:
#Establish a loss function for model evaluation
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [15]:
#Untrained model initial loss, probability close to random 1/10 for each class (-tf.math.log(1/10))
loss_fn(y_train[:1], predictions).numpy()

2.3615706

In [16]:
#model configuration and compiling, using adam optimiser, and accuracy metric
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [17]:
#Train the model
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2965 - accuracy: 0.9143
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1429 - accuracy: 0.9568
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1073 - accuracy: 0.9674
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0887 - accuracy: 0.9726
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0768 - accuracy: 0.9763


In [18]:
#Model evaluation based on test sets
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - loss: 0.0717 - accuracy: 0.9754 - 664ms/epoch - 2ms/step


[0.07172948122024536, 0.9753999710083008]

In [19]:
#Wrapping the trained model into a softmax top return probability
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [20]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[6.2623869e-08, 1.3561953e-07, 1.7529846e-05, 3.8205963e-04,
        9.7363000e-11, 9.9393546e-06, 4.9960809e-14, 9.9957591e-01,
        4.9299166e-07, 1.3818669e-05],
       [7.0136387e-08, 2.8870133e-04, 9.9970055e-01, 1.0047140e-05,
        2.0458368e-15, 3.2110086e-09, 4.4352211e-09, 2.8492337e-12,
        6.1157800e-07, 6.2321562e-13],
       [2.9040561e-07, 9.9928540e-01, 1.2390717e-04, 1.9793097e-06,
        4.4996473e-06, 4.4947492e-06, 1.5270849e-05, 4.3686052e-04,
        1.2687809e-04, 3.3553138e-07],
       [9.9966633e-01, 1.3214854e-09, 1.2560406e-04, 2.9884319e-07,
        4.7708352e-07, 9.2372356e-06, 2.4677054e-06, 9.8717770e-05,
        4.7879066e-08, 9.6820033e-05],
       [3.8545104e-06, 2.9969596e-09, 3.0027777e-06, 6.8928927e-07,
        9.7860670e-01, 1.9276963e-07, 4.4920504e-05, 2.4814569e-04,
        1.4266022e-05, 2.1078127e-02]], dtype=float32)>